name: publish-allure-pages

on:
  workflow_call:
    inputs:
      allure-results-artifact:
        type: string
        required: false
        default: "allure-results"

      report-folder:
        type: string
        required: true

jobs:
  publish-allure:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.allure-results-artifact }}
          path: allure-results

      - name: Load test report history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages/${{ inputs.report-folder }}
          allure_report: allure-report
          allure_history: allure-history/${{ inputs.report-folder }}
          keep_reports: '20'
          subfolder: gh-pages/${{ inputs.report-folder }}

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          keep_files: true
